dist: trusty
language: node_js
node_js:
  - 14

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v

install:
  - echo $REACT_APP_SRV_ADDR
  - yarn build
