dist: trusty
language: node_js
node_js:
  - 14

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - yarn global add @cloudbase/cli
  - tcb -v
  - tcb login --apiKeyId $id --apiKey $key

install:
  - echo $REACT_APP_SRV_ADDR
  - yarn install
  - REACT_APP_BUILD=`date +"%Y-%m-%d %H:%M.%S %Z"` CI=false yarn build

script:
  - echo "no need for unit test"

after_success:
  - tcb hosting delete cloudPath -e $envid
  - tcb hosting deploy build -e $envid
