dist: trusty
language: node_js
node_js:
  - 14

before_install:
  - wget http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64 -O /tmp/ossutil64
  - chmod 755 /tmp/ossutil64

install:
  - echo $REACT_APP_SRV_ADDR
  - yarn install
  - REACT_APP_BUILD=`date +"%Y-%m-%d %H:%M.%S %Z"` CI=false yarn build

script:
  - echo "no need for unit test"

after_success:
  - /tmp/ossutil64 --access-key-secret=$secret --access-key-id=$key --endpoint=$endpoint rm -rfs oss://$bucket
  - /tmp/ossutil64 --access-key-secret=$secret --access-key-id=$key --endpoint=$endpoint cp -r build/ oss://$bucket/
