dist: trusty
language: node_js
node_js:
  - 14

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - yarn global add @cloudbase/cli
  - tcb -v
  - tcb login --apiKeyId $id --apiKey $key

install:
  - echo $REACT_APP_SRV_ADDR
  - yarn install
  - CI=false yarn build
